image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: pip3 install -r requirements.txt # runs during prebuild
    command: echo 'start script'
